esphome:
  name: spacecowboypower
  friendly_name: "Smart PC Power Switch"
  name_add_mac_suffix: true

  project:
    name: chaos-engine.pcpower
    version: "0.2-20250731"
esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

  - platform: esphome
    password: "Flaynsr711"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
    password: "ghost123"
captive_portal:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://indianabutts/smart_pc_switch/esphome/pcswitch.yaml@v6
  import_full_config: false # or true
  
output:
  - platform: gpio
    id: scpower
    pin:
      number: GPIO0
      inverted: true
      
switch:
  - platform: template
    name: "Power Switch"
    lambda: |-
      if (id(power_state).state){
         return true;
      } else {
         return false;
      }
    turn_on_action:
      - output.turn_on: scpower
      - output.turn_off: scpower
    turn_off_action:
      - output.turn_on: scpower
      - delay: 500ms
      - output.turn_off: scpower
  - platform: template
    name: "Force Shutdown"
    turn_on_action:
      - output.turn_on: scpower
      - logger.log: "Waiting for Computer to turn off"
      - wait_until:
          binary_sensor.is_off: power_state
      - output.turn_off: scpower
      - logger.log: "Force Shutdown Complete"
    
        
binary_sensor:
  - platform: gpio
    id: power_state
    name: "PC Power"
    pin:
      number: GPIO2
    device_class: power
    
