esphome:
  name: spacecowboypower
esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Flaynsr711"

ota:
  - platform: esphome
    password: "Flaynsr711"

wifi:
  ssid: "75F4 Hyperoptic Fibre Broadband"
  password: "JXxGszHe2tgx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Spacecowboypower"
    password: "jrLdors1eBhJ"

output:
  - platform: gpio
    id: scpower
    pin:
      number: GPIO0
      inverted: true
      
switch:
  - platform: template
    name: "Power Switch"
    lambda: |-
      if (id(power_state).state){
         return true;
      } else {
         return false;
      }
    turn_on_action:
      - output.turn_on: scpower
      - delay: 500ms
      - output.turn_off: scpower
    turn_off_action:
      - output.turn_on: scpower
      - delay: 500ms
      - output.turn_off: scpower
        
binary_sensor:
  - platform: gpio
    id: power_state
    name: "PC Power"
    pin:
      number: GPIO2
    device_class: power
captive_portal:
    
