esphome:
  name: spacecowboypower
esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Flaynsr711"

ota:
  - platform: esphome
    password: "Flaynsr711"

wifi:
  ssid: "75F4 Hyperoptic Fibre Broadband"
  password: "JXxGszHe2tgx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Spacecowboypower"
    password: "jrLdors1eBhJ"
switch:
  - platform: gpio
    name: "Power Switch"
    id: scpower
    pin: 
      number: GPIO0
      inverted: true
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: scpower
binary_sensor:
  - platform: gpio
    id: power_state
    name: "PC Power"
    pin:
      number: GPIO2
    device_class: power
captive_portal:
    